CREATE TABLE V_PICK_LOCATIONS
(
  ID BIGINT PRIMARY KEY,
  X REAL,
  Y REAL,
  LINE VARCHAR(255),
  SCANCODE VARCHAR(255),
  DELVIERYID BIGINT,
  CUSTOMERID BIGINT,
  TRX BIGINT,
  COSEQ BIGINT,
  CLIENTID BIGINT,
  WRIN BIGINT,
  QUANTITY REAL,
  GOODSID BIGINT,
  WAREHOUSEID VARCHAR(255),
  LOCATION VARCHAR(255),
  PICKSEQ BIGINT,
  PICKZONEID VARCHAR(255),
  GRWEIGHT REAL,
  CBM REAL,
  REFILLEVENT INTEGER,
  QUANTITYBASE REAL,
  PSLIPTYPEID INTEGER,
  DPACK VARCHAR(255)
)

